#!/bin/zsh -li

export file="$1"
export dir="/pentest/targets/vulnscan"

ports=( 80 8080 443 )

vared -c -p "JSON or CSV: " type

echo "Will parse "$file" and save results in "$dir""

function parse () {
	if [[ -e "$dir"/"$port" ]]; then
		mv "$dir"/"$port" "$dir"/"$port".old
	fi

	if [[ "$type" = "json" ]]; then
		shodan parse --no-color --fields port,ip_str "$file" |egrep "^"$port"\b" |eh -4 -d |sort -u > "$dir"/"$port".new
		eh -4 -d "$dir"/"$port.new" "$dir"/"$port.old" > "$dir"/"$port"
		comm -23 "$dir"/"$port.new" "$dir"/"$port.old" > "$dir"/"$port".unique
	else
		csvcut -c Port,IP "$file" |egrep "^"$port"\b" |eh -4 -d |sort -u > "$dir"/"$port".new
		eh -4 -d "$dir"/"$port.new" "$dir"/"$port.old" > "$dir"/"$port"
		comm -23 "$dir"/"$port.new" "$dir"/"$port.old" > "$dir"/"$port".unique
	fi

}

function count () {
	# Totals
	echo "Totals:"
	echo ""$port"": $(eh -4 -d "$dir"/"$port"  |wc -l)""
	echo ""$port.new"": $(eh -4 -d "$dir"/"$port.new" |wc -l)""
	echo ""$port.old"": $(eh -4 -d "$dir"/"$port.old" |wc -l)""
	# Unique
	echo "Unique:"
	if [[ -e "$dir"/"$port".unique ]];then
		echo ""$port"": $(eh -4 -d "$dir"/"$port".unique  |wc -l)""
	fi
}

for port in "$ports[@]"; do
	parse
	count
done