#!/bin/zsh -li

export file="$1"

ports=( 80 8080 443 )

function parse () {

	if [[ -e "$port" ]]; then
		mv "$port" "$port".old
		csvcut -c port,ip,date "$file" |egrep "^"$port"\b" |eh -4 -d |sort -u > "$port".latest
		comm -23 "$port".latest "$port".old |sort -u > "$port".new
	else
		csvcut -c Port,IP "$file" |egrep "^"$port"\b" |eh -4 -d |sort -u > "$port".latest
	fi

	eh -4 -d "$port".* |sort -u >> "$port"
}

function count () {
	if [[ -e "$port".new ]];then
		echo ""$port" (new)": $(eh -4 -d "$port".new  |wc -l)""
		echo ""$port" (total)": $(eh -4 -d "$port"  |wc -l)""
	else
		echo ""$port" (total)": $(eh -4 -d "$port"  |wc -l)""
	fi

	rm "$port".{old,latest}
}

for port in "$ports[@]"; do
	parse
	count
done