#!/bin/zsh -li

ports=(
	80
	8080
	443
)

export log="$1"

function parse () {
	if [[ -e ./"$port" ]];then
		mv -vf /"$port" ./"$port".old
	fi

	egrep ":"$port"\b .*does not require" "$log" | eh -4 -d |sort -u > ./"$port".latest
}

function count () {
	wc -l ./"$port"
}

for port in $ports;do
	parse
	count
done
