#!/bin/zsh -li

ports=(
	80
	8080
	443
)

export log="$1"

function parse () {
	if [[ -e ./"$port" ]];then
		mv -vf ./"$port" ./"$port".old
		egrep ":"$port"\b .*does not require" "$log" | eh -4 -d |sort -u > ./"$port".latest
		comm -23 "$port".latest "$port".old |sort -u > "$port".new
	else
		egrep ":"$port"\b .*does not require" "$log" | eh -4 -d |sort -u > ./"$port"
	fi
}

function count () {
	if [[ -e "$port".new ]];then
		echo ""$port" (new)": $(eh -4 -d "$port".new  |wc -l)""
		echo ""$port" (total)": $(eh -4 -d "$port"  |wc -l)""
	else
		echo ""$port" (total)": $(eh -4 -d "$port"  |wc -l)""
	fi

	rm "$port".{old,latest}
}

for port in $ports;do
	parse
	count
done
