#!/bin/zsh -li

export file="$1"

ports=( 80 8080 443 )

function parse () {

	if [[ -e "$port" ]]; then
		mv "$port" "$port".old
		shodan parse --no-color --fields port,ip_str "$file" |egrep "^"$port"\b" |eh -4 -d |sort -u > "$port".new
		eh -4 -d "$port.new" "$port.old" |sort -u > "$port"
		rm *.new *old
	else
		shodan parse --no-color --fields port,ip_str "$file" |egrep "^"$port"\b" |eh -4 -d |sort -u > "$port"
	fi
}

function count () {
	for p in "${ports}";do
		echo ""$p"": $(eh -4 -d "$port"  |wc -l)""
	done
}

for port in "$ports[@]"; do
	parse
	count
done