#!/bin/zsh -li

export file="$1"

ports=( 80 8080 443 )

function parse () {

	if [[ -e "$port" ]]; then
		mv "$port" "$port".old
	fi

	csvcut -c Port,IP "$file" |egrep "^"$port"\b" |eh -4 -d |sort -u > "$port"
}

function count () {
	if [[ -e "$port".old ]];then
		comm -23 "$port" "$port".old > "$port".new
		eh -4 -d "$port" "$port".old > "$port".both
		wc -l "$port".new
		wc -l "$port".old
		wc -l "$port".both
		wc -l "$port"
	else
		wc -l "$port"
	fi
}

for port in "$ports[@]"; do
	parse
	count
done