#!/bin/zsh -li

vared -c -p "Countries: " countries
vared -c -p "After: " date

for cn in "$countries";do
	if [[ -e "$cn".json.gz ]]; then
		mv -vf "$cn".json.gz "$cn".json.gz.old
	fi

	shodan download --limit=30000 "$cn".json.gz jboss country:"$cn" after:"$date"
done